services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - db-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--password=${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5-fpm-alpine
    container_name: pma
    restart: unless-stopped
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    volumes:
      - pma_files:/var/www/html
      - pma_config:/etc/phpmyadmin:ro
    networks:
      - db-network
    depends_on:
      - mysql_db
  nginx:
    image: nginx:1.29.0-alpine
    container_name: nginx-ui
    restart: unless-stopped
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - pma_files:/var/www/html:ro
      - nginx_config:/etc/nginx/conf.d:ro
    networks:
      - db-network
    depends_on:
      - phpmyadmin

volumes:
  mysql-data:
  pma_files:
  pma_config:
  nginx_config:

networks:
  db-network:
